/**
 * Problem: Find the difference
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then adding ONE more letter at a random position.
 * Return the letter that was added to t.
 *
 * Example 1:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 */

public class FindTheDifference {
    public static void main(String[] args) {
        Solution solution = new Solution();
        System.out.println(solution.findTheDifference("abcd", "abcde")); // Output: e
    }
}

class Solution {
    public char findTheDifference(String s, String t) {
        char result = 0;

        for (char c : s.toCharArray()) {
            result = (char) (result ^ c);
        }

        for (char c : t.toCharArray()) {
            result = (char) (result ^ c);
        }

        return result;
        /* Since we are only adding one more letter at a random position,
         we can use the BITWISE OPERATOR XOR. If there were more than one additional letter,
         the output would differ because the bitwise values would be changed.

         The solution uses the bitwise XOR operator to find the added letter. XOR is a suitable approach because:

         - XORing a number with itself results in 0.
         - XORing a number with 0 results in the number itself.*/
    }
}
